version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: budget-app-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    networks:
      - budget-app-network

volumes:
  mongodb_data:

networks:
  budget-app-network:
    driver: bridge
